"""empty message

Revision ID: 74b3fb7fbe63
Revises: 
Create Date: 2021-04-03 17:42:43.691849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1d2e3e61e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(
                        length=40), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('hashed_password', sa.String(
                        length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('exercises',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('image', sa.String(length=100), nullable=True),
                    sa.Column('description', sa.String(
                        length=500), nullable=False),
                    sa.Column('reps', sa.Integer(), nullable=True),
                    sa.Column('sets', sa.Integer(), nullable=True),
                    sa.Column('timesPerWeek', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('categoryId', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['categoryId'], ['categories.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('questions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('promptId', sa.Integer(), nullable=False),
                    sa.Column('prompt', sa.String(length=500), nullable=True),
                    sa.Column('promptType', sa.String(
                        length=50), nullable=True),
                    sa.Column('displayText', sa.String(
                        length=50), nullable=True),
                    sa.Column('displayValue', sa.String(
                        length=50), nullable=True),
                    sa.Column('dx', sa.String(length=50), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('categoryId', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['categoryId'], ['categories.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('userexercises',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('userId', sa.Integer(), nullable=False),
                    sa.Column('exerciseId', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['exerciseId'], ['exercises.id'], ),
                    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('progresses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('reps', sa.Integer(), nullable=True),
                    sa.Column('sets', sa.Integer(), nullable=True),
                    sa.Column('weight', sa.Integer(), nullable=True),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('userExerciseId', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['userExerciseId'], [
                                            'userexercises.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progresses')
    op.drop_table('userexercises')
    op.drop_table('questions')
    op.drop_table('exercises')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
